- name: Play level variable
  hosts: all
  vars:
    URL: Play.example,com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

# if we declare a variable in play variable all the tasks can access that variable

- name: Play level variable from a file
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
          msg: URL = {{URL}}

- name: Task Level Variable
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
      vars:
        URL: hosts.example.com

# if we decleare a variable on tasklevel then only the task can access that variable


- name: Inventory Variable
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

- name: Fact variable
  hosts: all
  tasks:
    - name: Print Hostname
      ansible.builtin.debug:
        msg: Architecture = {{ansible_architecture}}, IP address= {{ansible_eth0.ipv4.address}}

- name: Register variable
  hosts: all
  tasks:
    - name: Run a shell command
      ansible.builtin.shell: uptime
      register: OUT

    - name: set a fact
      ansible.builtin.set_fact:
        OUTPUT: "{{OUT.stdout}}"

    - name: Print output of shell command
      ansible.builtin.debug:
        msg: "{{OUT}}"



