- name: Demo on Loops
  hosts: localhost
  tasks:
    - name: Print Fruit Name
      debug:
        msg: Fruit Name = {[item}}
      loop:
        - apple
        - bannana
        - orange
    - name: Print Fruit Name and Inventory Count
      debug:
        msg: Fruit Name = {{item.name }} , Avaliable Count = {{item.count}}
        loop:
          - {name: apple, count: 10}
          - {name: bannana, count: 10}
          - {name: orange, count: 10}


