- name: Configure YUM repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash -

- name: Install NodeJs
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Add Application User
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop Project Application User

- name: Download and Extract Frontend
  include_role:
    name: common
    tasks_from: download

- name: Cleanup Old Content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy App Content
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
  become_user: roboshop

- name: Install packages based on package.json.
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

- name: Copy Systemd File
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/catalogue.service

- name: Start Catalogue Service
  ansible.builtin.systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon-reload: yes